// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb.proto

/*
Package packet is a generated protocol buffer package.

It is generated from these files:
	pb.proto

It has these top-level messages:
	MqttHeader
	MqttConnect
	MqttConnAck
	MqttDisconnect
	MqttPublish
	MqttPubAck
	MqttSubscribe
	MqttSubAck
	MqttUnsubscribe
	MqttUnsubAck
	MqttPingReq
	MqttPingResp
*/
package packet

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MqttHeader struct {
	Dup    bool  `protobuf:"varint,1,opt,name=dup" json:"dup,omitempty"`
	Qos    int32 `protobuf:"varint,2,opt,name=qos" json:"qos,omitempty"`
	Retain bool  `protobuf:"varint,3,opt,name=retain" json:"retain,omitempty"`
}

func (m *MqttHeader) Reset()                    { *m = MqttHeader{} }
func (m *MqttHeader) String() string            { return proto.CompactTextString(m) }
func (*MqttHeader) ProtoMessage()               {}
func (*MqttHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MqttHeader) GetDup() bool {
	if m != nil {
		return m.Dup
	}
	return false
}

func (m *MqttHeader) GetQos() int32 {
	if m != nil {
		return m.Qos
	}
	return 0
}

func (m *MqttHeader) GetRetain() bool {
	if m != nil {
		return m.Retain
	}
	return false
}

type MqttConnect struct {
	Header         *MqttHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Id             string      `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Clean          bool        `protobuf:"varint,3,opt,name=clean" json:"clean,omitempty"`
	ClientId       []byte      `protobuf:"bytes,4,opt,name=clientId,proto3" json:"clientId,omitempty"`
	Username       []byte      `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	Password       []byte      `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	WillTopic      []byte      `protobuf:"bytes,7,opt,name=willTopic,proto3" json:"willTopic,omitempty"`
	WillPayload    []byte      `protobuf:"bytes,8,opt,name=willPayload,proto3" json:"willPayload,omitempty"`
	WillQos        int32       `protobuf:"varint,9,opt,name=willQos" json:"willQos,omitempty"`
	WillRetain     bool        `protobuf:"varint,10,opt,name=willRetain" json:"willRetain,omitempty"`
	KeepaliveTimer int32       `protobuf:"varint,11,opt,name=keepaliveTimer" json:"keepaliveTimer,omitempty"`
}

func (m *MqttConnect) Reset()                    { *m = MqttConnect{} }
func (m *MqttConnect) String() string            { return proto.CompactTextString(m) }
func (*MqttConnect) ProtoMessage()               {}
func (*MqttConnect) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MqttConnect) GetHeader() *MqttHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *MqttConnect) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MqttConnect) GetClean() bool {
	if m != nil {
		return m.Clean
	}
	return false
}

func (m *MqttConnect) GetClientId() []byte {
	if m != nil {
		return m.ClientId
	}
	return nil
}

func (m *MqttConnect) GetUsername() []byte {
	if m != nil {
		return m.Username
	}
	return nil
}

func (m *MqttConnect) GetPassword() []byte {
	if m != nil {
		return m.Password
	}
	return nil
}

func (m *MqttConnect) GetWillTopic() []byte {
	if m != nil {
		return m.WillTopic
	}
	return nil
}

func (m *MqttConnect) GetWillPayload() []byte {
	if m != nil {
		return m.WillPayload
	}
	return nil
}

func (m *MqttConnect) GetWillQos() int32 {
	if m != nil {
		return m.WillQos
	}
	return 0
}

func (m *MqttConnect) GetWillRetain() bool {
	if m != nil {
		return m.WillRetain
	}
	return false
}

func (m *MqttConnect) GetKeepaliveTimer() int32 {
	if m != nil {
		return m.KeepaliveTimer
	}
	return 0
}

type MqttConnAck struct {
	Header     *MqttHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	ReturnCode int32       `protobuf:"varint,2,opt,name=returnCode" json:"returnCode,omitempty"`
}

func (m *MqttConnAck) Reset()                    { *m = MqttConnAck{} }
func (m *MqttConnAck) String() string            { return proto.CompactTextString(m) }
func (*MqttConnAck) ProtoMessage()               {}
func (*MqttConnAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MqttConnAck) GetHeader() *MqttHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *MqttConnAck) GetReturnCode() int32 {
	if m != nil {
		return m.ReturnCode
	}
	return 0
}

type MqttDisconnect struct {
	Header *MqttHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Id     string      `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
}

func (m *MqttDisconnect) Reset()                    { *m = MqttDisconnect{} }
func (m *MqttDisconnect) String() string            { return proto.CompactTextString(m) }
func (*MqttDisconnect) ProtoMessage()               {}
func (*MqttDisconnect) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *MqttDisconnect) GetHeader() *MqttHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *MqttDisconnect) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type MqttPublish struct {
	Header    *MqttHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	MessageId int32       `protobuf:"varint,2,opt,name=messageId" json:"messageId,omitempty"`
	Topic     []byte      `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	Payload   []byte      `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *MqttPublish) Reset()                    { *m = MqttPublish{} }
func (m *MqttPublish) String() string            { return proto.CompactTextString(m) }
func (*MqttPublish) ProtoMessage()               {}
func (*MqttPublish) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *MqttPublish) GetHeader() *MqttHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *MqttPublish) GetMessageId() int32 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

func (m *MqttPublish) GetTopic() []byte {
	if m != nil {
		return m.Topic
	}
	return nil
}

func (m *MqttPublish) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type MqttPubAck struct {
	Header    *MqttHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	MessageId int32       `protobuf:"varint,2,opt,name=messageId" json:"messageId,omitempty"`
}

func (m *MqttPubAck) Reset()                    { *m = MqttPubAck{} }
func (m *MqttPubAck) String() string            { return proto.CompactTextString(m) }
func (*MqttPubAck) ProtoMessage()               {}
func (*MqttPubAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *MqttPubAck) GetHeader() *MqttHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *MqttPubAck) GetMessageId() int32 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

type MqttSubscribe struct {
	Header    *MqttHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	MessageId int32       `protobuf:"varint,2,opt,name=messageId" json:"messageId,omitempty"`
	Topic     [][]byte    `protobuf:"bytes,3,rep,name=topic,proto3" json:"topic,omitempty"`
	Qos       []int32     `protobuf:"varint,4,rep,packed,name=qos" json:"qos,omitempty"`
}

func (m *MqttSubscribe) Reset()                    { *m = MqttSubscribe{} }
func (m *MqttSubscribe) String() string            { return proto.CompactTextString(m) }
func (*MqttSubscribe) ProtoMessage()               {}
func (*MqttSubscribe) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *MqttSubscribe) GetHeader() *MqttHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *MqttSubscribe) GetMessageId() int32 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

func (m *MqttSubscribe) GetTopic() [][]byte {
	if m != nil {
		return m.Topic
	}
	return nil
}

func (m *MqttSubscribe) GetQos() []int32 {
	if m != nil {
		return m.Qos
	}
	return nil
}

type MqttSubAck struct {
	Header    *MqttHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	MessageId int32       `protobuf:"varint,2,opt,name=messageId" json:"messageId,omitempty"`
	Qos       []int32     `protobuf:"varint,3,rep,packed,name=qos" json:"qos,omitempty"`
}

func (m *MqttSubAck) Reset()                    { *m = MqttSubAck{} }
func (m *MqttSubAck) String() string            { return proto.CompactTextString(m) }
func (*MqttSubAck) ProtoMessage()               {}
func (*MqttSubAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *MqttSubAck) GetHeader() *MqttHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *MqttSubAck) GetMessageId() int32 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

func (m *MqttSubAck) GetQos() []int32 {
	if m != nil {
		return m.Qos
	}
	return nil
}

type MqttUnsubscribe struct {
	Header    *MqttHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	MessageId int32       `protobuf:"varint,2,opt,name=messageId" json:"messageId,omitempty"`
	Topic     [][]byte    `protobuf:"bytes,3,rep,name=topic,proto3" json:"topic,omitempty"`
}

func (m *MqttUnsubscribe) Reset()                    { *m = MqttUnsubscribe{} }
func (m *MqttUnsubscribe) String() string            { return proto.CompactTextString(m) }
func (*MqttUnsubscribe) ProtoMessage()               {}
func (*MqttUnsubscribe) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *MqttUnsubscribe) GetHeader() *MqttHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *MqttUnsubscribe) GetMessageId() int32 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

func (m *MqttUnsubscribe) GetTopic() [][]byte {
	if m != nil {
		return m.Topic
	}
	return nil
}

type MqttUnsubAck struct {
	Header    *MqttHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	MessageId int32       `protobuf:"varint,2,opt,name=messageId" json:"messageId,omitempty"`
}

func (m *MqttUnsubAck) Reset()                    { *m = MqttUnsubAck{} }
func (m *MqttUnsubAck) String() string            { return proto.CompactTextString(m) }
func (*MqttUnsubAck) ProtoMessage()               {}
func (*MqttUnsubAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *MqttUnsubAck) GetHeader() *MqttHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *MqttUnsubAck) GetMessageId() int32 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

type MqttPingReq struct {
	Header *MqttHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
}

func (m *MqttPingReq) Reset()                    { *m = MqttPingReq{} }
func (m *MqttPingReq) String() string            { return proto.CompactTextString(m) }
func (*MqttPingReq) ProtoMessage()               {}
func (*MqttPingReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *MqttPingReq) GetHeader() *MqttHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type MqttPingResp struct {
	Header *MqttHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
}

func (m *MqttPingResp) Reset()                    { *m = MqttPingResp{} }
func (m *MqttPingResp) String() string            { return proto.CompactTextString(m) }
func (*MqttPingResp) ProtoMessage()               {}
func (*MqttPingResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *MqttPingResp) GetHeader() *MqttHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func init() {
	proto.RegisterType((*MqttHeader)(nil), "packet.MqttHeader")
	proto.RegisterType((*MqttConnect)(nil), "packet.MqttConnect")
	proto.RegisterType((*MqttConnAck)(nil), "packet.MqttConnAck")
	proto.RegisterType((*MqttDisconnect)(nil), "packet.MqttDisconnect")
	proto.RegisterType((*MqttPublish)(nil), "packet.MqttPublish")
	proto.RegisterType((*MqttPubAck)(nil), "packet.MqttPubAck")
	proto.RegisterType((*MqttSubscribe)(nil), "packet.MqttSubscribe")
	proto.RegisterType((*MqttSubAck)(nil), "packet.MqttSubAck")
	proto.RegisterType((*MqttUnsubscribe)(nil), "packet.MqttUnsubscribe")
	proto.RegisterType((*MqttUnsubAck)(nil), "packet.MqttUnsubAck")
	proto.RegisterType((*MqttPingReq)(nil), "packet.MqttPingReq")
	proto.RegisterType((*MqttPingResp)(nil), "packet.MqttPingResp")
}

func init() { proto.RegisterFile("pb.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 464 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x54, 0xcf, 0x6f, 0xd3, 0x30,
	0x14, 0x56, 0x9a, 0xb5, 0x6b, 0x5f, 0x47, 0x41, 0x16, 0x42, 0x16, 0x9a, 0xa6, 0xc8, 0x07, 0x54,
	0x71, 0xe8, 0x01, 0x4e, 0x70, 0x43, 0xe3, 0xb0, 0x49, 0x20, 0x95, 0x6c, 0x20, 0x38, 0x3a, 0xf1,
	0xd3, 0x6a, 0x35, 0x8d, 0x5d, 0xdb, 0x61, 0xe2, 0xc8, 0x89, 0xbf, 0x90, 0xff, 0x07, 0xd9, 0x4e,
	0x96, 0x8a, 0x03, 0x52, 0xc4, 0xe0, 0xe6, 0xef, 0x7b, 0xf1, 0xf7, 0xbd, 0x5f, 0x0e, 0x4c, 0x75,
	0xb1, 0xd2, 0x46, 0x39, 0x45, 0x26, 0x9a, 0x97, 0x5b, 0x74, 0xec, 0x02, 0xe0, 0xfd, 0xde, 0xb9,
	0x0b, 0xe4, 0x02, 0x0d, 0x79, 0x04, 0xa9, 0x68, 0x34, 0x4d, 0xb2, 0x64, 0x39, 0xcd, 0xfd, 0xd1,
	0x33, 0x7b, 0x65, 0xe9, 0x28, 0x4b, 0x96, 0xe3, 0xdc, 0x1f, 0xc9, 0x13, 0x98, 0x18, 0x74, 0x5c,
	0xd6, 0x34, 0x0d, 0x9f, 0xb5, 0x88, 0xfd, 0x1c, 0xc1, 0xdc, 0x4b, 0x9d, 0xab, 0xba, 0xc6, 0xd2,
	0x91, 0xe7, 0x30, 0xd9, 0x04, 0xd5, 0x20, 0x37, 0x7f, 0x41, 0x56, 0xd1, 0x72, 0xd5, 0xfb, 0xe5,
	0xed, 0x17, 0x64, 0x01, 0x23, 0x29, 0x82, 0xc9, 0x2c, 0x1f, 0x49, 0x41, 0x1e, 0xc3, 0xb8, 0xac,
	0x90, 0x77, 0x16, 0x11, 0x90, 0xa7, 0x30, 0x2d, 0x2b, 0x89, 0xb5, 0xbb, 0x14, 0xf4, 0x28, 0x4b,
	0x96, 0x27, 0xf9, 0x1d, 0xf6, 0xb1, 0xc6, 0xa2, 0xa9, 0xf9, 0x0e, 0xe9, 0x38, 0xc6, 0x3a, 0xec,
	0x63, 0x9a, 0x5b, 0x7b, 0xab, 0x8c, 0xa0, 0x93, 0x18, 0xeb, 0x30, 0x39, 0x85, 0xd9, 0xad, 0xac,
	0xaa, 0x6b, 0xa5, 0x65, 0x49, 0x8f, 0x43, 0xb0, 0x27, 0x48, 0x06, 0x73, 0x0f, 0xd6, 0xfc, 0x5b,
	0xa5, 0xb8, 0xa0, 0xd3, 0x10, 0x3f, 0xa4, 0x08, 0x85, 0x63, 0x0f, 0x3f, 0x28, 0x4b, 0x67, 0xa1,
	0x47, 0x1d, 0x24, 0x67, 0x00, 0xfe, 0x98, 0xc7, 0x5e, 0x41, 0x28, 0xe4, 0x80, 0x21, 0xcf, 0x60,
	0xb1, 0x45, 0xd4, 0xbc, 0x92, 0x5f, 0xf1, 0x5a, 0xee, 0xd0, 0xd0, 0x79, 0x10, 0xf8, 0x8d, 0x65,
	0x5f, 0xfa, 0xb6, 0xbe, 0x29, 0xb7, 0x83, 0xda, 0x7a, 0x06, 0x60, 0xd0, 0x35, 0xa6, 0x3e, 0x57,
	0x02, 0xdb, 0x19, 0x1e, 0x30, 0xec, 0x1d, 0x2c, 0xfc, 0xad, 0xb7, 0xd2, 0x96, 0x7f, 0x3f, 0x34,
	0xf6, 0x23, 0x89, 0x99, 0xae, 0x9b, 0xa2, 0x92, 0x76, 0x33, 0x48, 0xeb, 0x14, 0x66, 0x3b, 0xb4,
	0x96, 0xdf, 0xe0, 0xa5, 0x68, 0x13, 0xed, 0x09, 0xbf, 0x0e, 0x2e, 0x0c, 0x28, 0x0d, 0x03, 0x88,
	0xc0, 0xb7, 0x5e, 0xb7, 0x83, 0x89, 0xdb, 0xd0, 0x41, 0xf6, 0x29, 0x2e, 0xf5, 0xba, 0x29, 0x86,
	0x76, 0xec, 0x8f, 0x79, 0xb0, 0xef, 0x09, 0x3c, 0xf0, 0x97, 0xae, 0x9a, 0xc2, 0x96, 0x46, 0x16,
	0xf8, 0x6f, 0x6a, 0x4c, 0xfb, 0x1a, 0xdb, 0xe7, 0x77, 0x94, 0xa5, 0xed, 0xf3, 0x63, 0x9b, 0x58,
	0xdb, 0xd5, 0x3d, 0xd7, 0xd6, 0x39, 0xa5, 0xbd, 0xd3, 0x1e, 0x1e, 0x7a, 0x95, 0x8f, 0xb5, 0xfd,
	0x5f, 0xe5, 0xb2, 0xcf, 0x70, 0x72, 0x67, 0x79, 0xbf, 0xa3, 0x7b, 0xd5, 0xee, 0xa6, 0xac, 0x6f,
	0x72, 0xdc, 0x0f, 0x11, 0x66, 0xaf, 0x63, 0x52, 0xf1, 0xaa, 0xd5, 0x43, 0xee, 0x16, 0x93, 0xf0,
	0xb7, 0x7d, 0xf9, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xac, 0x31, 0x6a, 0xf0, 0x79, 0x05, 0x00, 0x00,
}
