// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	pb.proto

It has these top-level messages:
	MqttConnect
	MqttConnack
	MqttDisconnect
	MqttPublish
	MqttPuback
	MqttSubscribe
	MqttSuback
	MqttUnsubscribe
	MqttUnsuback
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MqttConnect struct {
	Id             string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Clean          bool   `protobuf:"varint,2,opt,name=clean" json:"clean,omitempty"`
	ClientId       string `protobuf:"bytes,3,opt,name=clientId" json:"clientId,omitempty"`
	Username       string `protobuf:"bytes,4,opt,name=username" json:"username,omitempty"`
	Password       string `protobuf:"bytes,5,opt,name=password" json:"password,omitempty"`
	WillTopic      string `protobuf:"bytes,6,opt,name=willTopic" json:"willTopic,omitempty"`
	WillPayload    string `protobuf:"bytes,7,opt,name=willPayload" json:"willPayload,omitempty"`
	WillQos        []byte `protobuf:"bytes,8,opt,name=willQos,proto3" json:"willQos,omitempty"`
	WillRetain     bool   `protobuf:"varint,9,opt,name=willRetain" json:"willRetain,omitempty"`
	KeepaliveTimer int32  `protobuf:"varint,10,opt,name=keepaliveTimer" json:"keepaliveTimer,omitempty"`
}

func (m *MqttConnect) Reset()                    { *m = MqttConnect{} }
func (m *MqttConnect) String() string            { return proto.CompactTextString(m) }
func (*MqttConnect) ProtoMessage()               {}
func (*MqttConnect) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MqttConnect) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MqttConnect) GetClean() bool {
	if m != nil {
		return m.Clean
	}
	return false
}

func (m *MqttConnect) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *MqttConnect) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *MqttConnect) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *MqttConnect) GetWillTopic() string {
	if m != nil {
		return m.WillTopic
	}
	return ""
}

func (m *MqttConnect) GetWillPayload() string {
	if m != nil {
		return m.WillPayload
	}
	return ""
}

func (m *MqttConnect) GetWillQos() []byte {
	if m != nil {
		return m.WillQos
	}
	return nil
}

func (m *MqttConnect) GetWillRetain() bool {
	if m != nil {
		return m.WillRetain
	}
	return false
}

func (m *MqttConnect) GetKeepaliveTimer() int32 {
	if m != nil {
		return m.KeepaliveTimer
	}
	return 0
}

type MqttConnack struct {
	ReturnCode []byte `protobuf:"bytes,1,opt,name=returnCode,proto3" json:"returnCode,omitempty"`
}

func (m *MqttConnack) Reset()                    { *m = MqttConnack{} }
func (m *MqttConnack) String() string            { return proto.CompactTextString(m) }
func (*MqttConnack) ProtoMessage()               {}
func (*MqttConnack) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MqttConnack) GetReturnCode() []byte {
	if m != nil {
		return m.ReturnCode
	}
	return nil
}

type MqttDisconnect struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *MqttDisconnect) Reset()                    { *m = MqttDisconnect{} }
func (m *MqttDisconnect) String() string            { return proto.CompactTextString(m) }
func (*MqttDisconnect) ProtoMessage()               {}
func (*MqttDisconnect) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MqttDisconnect) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type MqttPublish struct {
	MessageId int32  `protobuf:"varint,1,opt,name=messageId" json:"messageId,omitempty"`
	Topic     string `protobuf:"bytes,2,opt,name=topic" json:"topic,omitempty"`
	Qos       []byte `protobuf:"bytes,3,opt,name=qos,proto3" json:"qos,omitempty"`
	Payload   string `protobuf:"bytes,4,opt,name=payload" json:"payload,omitempty"`
	Retain    bool   `protobuf:"varint,5,opt,name=retain" json:"retain,omitempty"`
}

func (m *MqttPublish) Reset()                    { *m = MqttPublish{} }
func (m *MqttPublish) String() string            { return proto.CompactTextString(m) }
func (*MqttPublish) ProtoMessage()               {}
func (*MqttPublish) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *MqttPublish) GetMessageId() int32 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

func (m *MqttPublish) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *MqttPublish) GetQos() []byte {
	if m != nil {
		return m.Qos
	}
	return nil
}

func (m *MqttPublish) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

func (m *MqttPublish) GetRetain() bool {
	if m != nil {
		return m.Retain
	}
	return false
}

type MqttPuback struct {
	MessageId int32 `protobuf:"varint,1,opt,name=messageId" json:"messageId,omitempty"`
}

func (m *MqttPuback) Reset()                    { *m = MqttPuback{} }
func (m *MqttPuback) String() string            { return proto.CompactTextString(m) }
func (*MqttPuback) ProtoMessage()               {}
func (*MqttPuback) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *MqttPuback) GetMessageId() int32 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

type MqttSubscribe struct {
	MessageId int32    `protobuf:"varint,1,opt,name=messageId" json:"messageId,omitempty"`
	Topic     []string `protobuf:"bytes,2,rep,name=topic" json:"topic,omitempty"`
	Qos       [][]byte `protobuf:"bytes,3,rep,name=qos,proto3" json:"qos,omitempty"`
}

func (m *MqttSubscribe) Reset()                    { *m = MqttSubscribe{} }
func (m *MqttSubscribe) String() string            { return proto.CompactTextString(m) }
func (*MqttSubscribe) ProtoMessage()               {}
func (*MqttSubscribe) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *MqttSubscribe) GetMessageId() int32 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

func (m *MqttSubscribe) GetTopic() []string {
	if m != nil {
		return m.Topic
	}
	return nil
}

func (m *MqttSubscribe) GetQos() [][]byte {
	if m != nil {
		return m.Qos
	}
	return nil
}

type MqttSuback struct {
	MessageId int32    `protobuf:"varint,1,opt,name=messageId" json:"messageId,omitempty"`
	Qos       [][]byte `protobuf:"bytes,3,rep,name=qos,proto3" json:"qos,omitempty"`
}

func (m *MqttSuback) Reset()                    { *m = MqttSuback{} }
func (m *MqttSuback) String() string            { return proto.CompactTextString(m) }
func (*MqttSuback) ProtoMessage()               {}
func (*MqttSuback) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *MqttSuback) GetMessageId() int32 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

func (m *MqttSuback) GetQos() [][]byte {
	if m != nil {
		return m.Qos
	}
	return nil
}

type MqttUnsubscribe struct {
	MessageId int32    `protobuf:"varint,1,opt,name=messageId" json:"messageId,omitempty"`
	Topic     []string `protobuf:"bytes,2,rep,name=topic" json:"topic,omitempty"`
}

func (m *MqttUnsubscribe) Reset()                    { *m = MqttUnsubscribe{} }
func (m *MqttUnsubscribe) String() string            { return proto.CompactTextString(m) }
func (*MqttUnsubscribe) ProtoMessage()               {}
func (*MqttUnsubscribe) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *MqttUnsubscribe) GetMessageId() int32 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

func (m *MqttUnsubscribe) GetTopic() []string {
	if m != nil {
		return m.Topic
	}
	return nil
}

type MqttUnsuback struct {
	MessageId int32 `protobuf:"varint,1,opt,name=messageId" json:"messageId,omitempty"`
}

func (m *MqttUnsuback) Reset()                    { *m = MqttUnsuback{} }
func (m *MqttUnsuback) String() string            { return proto.CompactTextString(m) }
func (*MqttUnsuback) ProtoMessage()               {}
func (*MqttUnsuback) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *MqttUnsuback) GetMessageId() int32 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

func init() {
	proto.RegisterType((*MqttConnect)(nil), "MqttConnect")
	proto.RegisterType((*MqttConnack)(nil), "MqttConnack")
	proto.RegisterType((*MqttDisconnect)(nil), "MqttDisconnect")
	proto.RegisterType((*MqttPublish)(nil), "MqttPublish")
	proto.RegisterType((*MqttPuback)(nil), "MqttPuback")
	proto.RegisterType((*MqttSubscribe)(nil), "MqttSubscribe")
	proto.RegisterType((*MqttSuback)(nil), "MqttSuback")
	proto.RegisterType((*MqttUnsubscribe)(nil), "MqttUnsubscribe")
	proto.RegisterType((*MqttUnsuback)(nil), "MqttUnsuback")
}

func init() { proto.RegisterFile("pb.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 385 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0xd1, 0xea, 0xd3, 0x30,
	0x18, 0xc5, 0x69, 0x6b, 0xb7, 0xee, 0x5b, 0x9d, 0x12, 0x44, 0x82, 0x88, 0x94, 0x5c, 0x48, 0x11,
	0xf5, 0xc6, 0x5b, 0xef, 0xa6, 0x17, 0xbb, 0x10, 0x66, 0xb6, 0x3d, 0x40, 0xda, 0x06, 0x0d, 0xeb,
	0x92, 0x2e, 0x49, 0x1d, 0x3e, 0x80, 0x0f, 0xe3, 0x5b, 0x4a, 0x92, 0x76, 0x1b, 0x32, 0x74, 0xf0,
	0xbf, 0xeb, 0x39, 0xe7, 0xcb, 0xc7, 0xc9, 0x2f, 0x14, 0xb2, 0xae, 0x7a, 0xdf, 0x69, 0x65, 0x15,
	0xf9, 0x1d, 0xc3, 0xfc, 0xcb, 0xd1, 0xda, 0xa5, 0x92, 0x92, 0xd7, 0x16, 0x2d, 0x20, 0x16, 0x0d,
	0x8e, 0x8a, 0xa8, 0x9c, 0xd1, 0x58, 0x34, 0xe8, 0x19, 0xa4, 0x75, 0xcb, 0x99, 0xc4, 0x71, 0x11,
	0x95, 0x19, 0x0d, 0x02, 0xbd, 0x80, 0xac, 0x6e, 0x05, 0x97, 0x76, 0xd5, 0xe0, 0xc4, 0xcf, 0x9e,
	0xb5, 0xcb, 0x7a, 0xc3, 0xb5, 0x64, 0x07, 0x8e, 0x1f, 0x85, 0x6c, 0xd4, 0x2e, 0xeb, 0x98, 0x31,
	0x27, 0xa5, 0x1b, 0x9c, 0x86, 0x6c, 0xd4, 0xe8, 0x25, 0xcc, 0x4e, 0xa2, 0x6d, 0xb7, 0xaa, 0x13,
	0x35, 0x9e, 0xf8, 0xf0, 0x62, 0xa0, 0x02, 0xe6, 0x4e, 0xac, 0xd9, 0xcf, 0x56, 0xb1, 0x06, 0x4f,
	0x7d, 0x7e, 0x6d, 0x21, 0x0c, 0x53, 0x27, 0xbf, 0x2a, 0x83, 0xb3, 0x22, 0x2a, 0x73, 0x3a, 0x4a,
	0xf4, 0x0a, 0xc0, 0x7d, 0x52, 0x6e, 0x99, 0x90, 0x78, 0xe6, 0x2f, 0x72, 0xe5, 0xa0, 0xd7, 0xb0,
	0xd8, 0x73, 0xde, 0xb1, 0x56, 0xfc, 0xe0, 0x5b, 0x71, 0xe0, 0x1a, 0x43, 0x11, 0x95, 0x29, 0xfd,
	0xcb, 0x25, 0xef, 0x2e, 0xa8, 0x58, 0xbd, 0x77, 0x6b, 0x35, 0xb7, 0xbd, 0x96, 0x4b, 0xd5, 0x70,
	0x8f, 0x2c, 0xa7, 0x57, 0x0e, 0x29, 0x60, 0xe1, 0xc6, 0x3f, 0x09, 0x53, 0xdf, 0x86, 0x4b, 0x7e,
	0x45, 0x61, 0xe3, 0xba, 0xaf, 0x5a, 0x61, 0xbe, 0x3b, 0x04, 0x07, 0x6e, 0x0c, 0xfb, 0xc6, 0x57,
	0x61, 0x2c, 0xa5, 0x17, 0xc3, 0x3d, 0x85, 0xf5, 0x70, 0x62, 0xbf, 0x20, 0x08, 0xf4, 0x14, 0x92,
	0xa3, 0x32, 0xfe, 0x15, 0x72, 0xea, 0x3e, 0x1d, 0x88, 0x6e, 0xc0, 0x14, 0xf8, 0x8f, 0x12, 0x3d,
	0x87, 0x89, 0x0e, 0x10, 0x52, 0x0f, 0x61, 0x50, 0xe4, 0x0d, 0xc0, 0x50, 0xc3, 0xdd, 0xeb, 0x9f,
	0x2d, 0xc8, 0x0e, 0x1e, 0xbb, 0xd9, 0x4d, 0x5f, 0x99, 0x5a, 0x8b, 0x8a, 0xdf, 0x5f, 0x3a, 0xb9,
	0x51, 0x3a, 0x19, 0x4a, 0x93, 0x8f, 0xa1, 0xc2, 0xe6, 0x8e, 0x0a, 0x37, 0x4e, 0x7f, 0x86, 0x27,
	0xee, 0xf4, 0x4e, 0x9a, 0x87, 0xd4, 0x22, 0x6f, 0x21, 0x3f, 0xaf, 0xf9, 0x6f, 0x8d, 0x6a, 0xe2,
	0xff, 0xa0, 0x0f, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x45, 0x6f, 0x24, 0x2e, 0x4d, 0x03, 0x00,
	0x00,
}
